#include <bitmap.h>
#include <string.h>
#include <stdio.h>
#include "ssd1306.h"
int bitmapIterator = 0;
//------------------------------------------------------------------------------
// Table generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

void drawNextBitmap()
{
	ssd1306_Fill(Black);
	switch(bitmapIterator)
	{
	case 0:
		ssd1306_DrawBitmap(0,0,twins128x64,128,64,White); //gut
	break;
	case 1:
	    ssd1306_DrawBitmap(32, 0, hearth64x64, 64, 64, White);
	break;
	case 2:
	    ssd1306_DrawBitmap(32, 0, brittle64x64, 64, 64, White); //gut
	break;
	case 3:
	    ssd1306_DrawBitmap(32, 0, giants64x64, 64, 64, White); //gut
	break;
	case 4:
	    ssd1306_DrawBitmap(32,0,bramble64x64,64,64,White);
	break;
	case 5:
		ssd1306_DrawBitmap(32,0,eye64x64,64,64,White);
	break;
	case 6:
		ssd1306_DrawBitmap(32,0,sun64x64,64,64,White);
	break;


	}
	bitmapIterator++;
	if(bitmapIterator > 6) bitmapIterator = 0;

}
void drawLogo()
{
	ssd1306_Fill(White);
    ssd1306_DrawBitmap(0,0,outerwilds128x64,128,64,Black);

}
